// Generated from the "Vault Reference Table" sheet of the WAG Open Scoring SV Calculator.
// dv = D score (start value is dv + 10).
export const VAULTS = [
  {"name": "Front Handspring", "entry": "Front Entry w/o Salto", "usag": "1.101", "dv": 2.4},
  {"name": "FHS onto board - Ft. Hspr. Off", "entry": "Front Entry w/o Salto", "usag": "1.109", "dv": 2.4},
  {"name": "Ft. Hspr. 1/2 Off", "entry": "Front Entry w/o Salto", "usag": "1.102", "dv": 3.0},
  {"name": "FHS onto board - Ft. Hspr. 1/2 Off", "entry": "Front Entry w/o Salto", "usag": "1.110", "dv": 3.0},
  {"name": "Ft. Hspr. 1/1 Off", "entry": "Front Entry w/o Salto", "usag": "1.201", "dv": 3.9},
  {"name": "FHS onto board - Ft. Hspr. 1/1 Off", "entry": "Front Entry w/o Salto", "usag": "1.209", "dv": 3.9},
  {"name": "Ft. Hspr. 3/2 Off", "entry": "Front Entry w/o Salto", "usag": "1.202", "dv": 4.8},
  {"name": "Ft. Hspr. 2/1 Off", "entry": "Front Entry w/o Salto", "usag": "1.301", "dv": 5.4},
  {"name": "Ft. Hspr. 5/2 Off", "entry": "Front Entry w/o Salto", "usag": "1.402", "dv": 6.0},
  {"name": "FHS onto board - 1/2 On - Repulsion Off", "entry": "Front Entry w/o Salto", "usag": "1.111", "dv": 2.4},
  {"name": "Yamashita", "entry": "Front Entry w/o Salto", "usag": "1.103", "dv": 3.0},
  {"name": "Yamashita - 1/2 Off", "entry": "Front Entry w/o Salto", "usag": "1.104", "dv": 3.6},
  {"name": "Yamashita - 1/1 Off", "entry": "Front Entry w/o Salto", "usag": "1.203", "dv": 4.2},
  {"name": "Yamashita - 5/2 Off", "entry": "Front Entry w/o Salto", "usag": "1.504", "dv": 6.0},
  {"name": "1/4 On - 1/4 Off (land facing table)", "entry": "1/2 On Entry w/o Salto", "usag": "1.108", "dv": 2.4},
  {"name": "1/2 On - Repulsion Off", "entry": "1/2 On Entry w/o Salto", "usag": "1.106", "dv": 2.4},
  {"name": "1/2 On - 1/2 Off", "entry": "1/2 On Entry w/o Salto", "usag": "1.105", "dv": 3.6},
  {"name": "FHS onto board - 1/2 On - 1/2 Off", "entry": "1/2 On Entry w/o Salto", "usag": "1.211", "dv": 3.6},
  {"name": "1/2 On - 1/1 Off", "entry": "1/2 On Entry w/o Salto", "usag": "1.206", "dv": 3.9},
  {"name": "FHS onto board - 1/2 On - 1/1 Off", "entry": "1/2 On Entry w/o Salto", "usag": "1.311", "dv": 3.9},
  {"name": "1/2 On - 3/2 Off", "entry": "1/2 On Entry w/o Salto", "usag": "1.205", "dv": 4.8},
  {"name": "1/2 On - 2/1 Off", "entry": "1/2 On Entry w/o Salto", "usag": "1.306", "dv": 5.4},
  {"name": "1/1 On - Fr. Hspr. Off", "entry": "1/2 On Entry w/o Salto", "usag": "1.206", "dv": 4.8},
  {"name": "1/1 On - 1/2 Off", "entry": "1/1 On Entry w/o Salto", "usag": "1.208", "dv": 5.1},
  {"name": "1/1 On - 1/1 Off", "entry": "1/1 On Entry w/o Salto", "usag": "1.307", "dv": 5.4},
  {"name": "1/1 On - 3/2 Off", "entry": "1/1 On Entry w/o Salto", "usag": "1.308", "dv": 6.0},
  {"name": "RO-FF - Repulsion Off (Yurchenko Timer)", "entry": "Roundoff entry w/o Salto", "usag": "4.101", "dv": 3.0},
  {"name": "RO-FF; 1/2 Off", "entry": "Roundoff entry w/o Salto", "usag": "4.402", "dv": 3.6},
  {"name": "RO-FF; 1/1 Off", "entry": "Roundoff entry w/o Salto", "usag": "4.201", "dv": 4.2},
  {"name": "RO-FF; 3/2 Off", "entry": "Roundoff entry w/o Salto", "usag": "4.202", "dv": 4.8},
  {"name": "RO-FF; 2/1 Off", "entry": "Roundoff entry w/o Salto", "usag": "4.301", "dv": 5.4},
  {"name": "RO-FF 1/2 On - Handspring Off", "entry": "Roundoff 1/2 On entry w/o Salto", "usag": "5.101", "dv": 3.3},
  {"name": "RO-FF 1/2 On - Hspr.1/2 Off", "entry": "Roundoff 1/2 On entry w/o Salto", "usag": "5.102", "dv": 3.9},
  {"name": "RO-FF 1/2 On - Hspr.1/1 Off", "entry": "Roundoff 1/2 On entry w/o Salto", "usag": "5.201", "dv": 4.5},
  {"name": "RO-FF 1/2 On - Hspr.3/2 Off", "entry": "Roundoff 1/2 On entry w/o Salto", "usag": "5.202", "dv": 5.1},
  {"name": "RO-FF 1/1 On - Handspring Off", "entry": "Roundoff 1/2 On entry w/o Salto", "usag": "5.101", "dv": 3.6},
  {"name": "RO-FF 1/1 On - Hspr.1/2 Off", "entry": "Roundoff 1/2 On entry w/o Salto", "usag": "5.107", "dv": 4.2},
  {"name": "RO-FF 1/1 On - Hspr.1/1 Off", "entry": "Roundoff 1/2 On entry w/o Salto", "usag": "5.207", "dv": 4.8},
  {"name": "RO-FF 1/2 On - Hspr.2/1 Off", "entry": "Roundoff 1/2 On entry w/o Salto", "usag": "5.312", "dv": 5.7},
  {"name": "Ft. Hspr. - Front Tuck", "entry": "FHS w/ Saltos", "usag": "2.301", "dv": 5.4},
  {"name": "FHS onto board - Ft. Hspr. - Front Tuck", "entry": "FHS w/ Saltos", "usag": "2.310", "dv": 5.4},
  {"name": "Ft. Hspr. - Front Tuck 1/2", "entry": "FHS w/ Saltos", "usag": "2.302", "dv": 5.7},
  {"name": "FHS onto board - Ft. Hspr. - Front Tuck 1/2", "entry": "FHS w/ Saltos", "usag": "2.410", "dv": 5.7},
  {"name": "Ft. Hspr. - 1/2 to Back Tuck", "entry": "FHS w/ Saltos", "usag": "2.303", "dv": 5.7},
  {"name": "Ft. Hspr. - Front Tuck 1/1", "entry": "FHS w/ Saltos", "usag": "2.402", "dv": 6.3},
  {"name": "Ft. Hspr. - 1/2 to Back Tuck 1/2", "entry": "FHS w/ Saltos", "usag": "2.403", "dv": 6.3},
  {"name": "Ft. Hspr. - Front Tuck 3/2", "entry": "FHS w/ Saltos", "usag": "2.502", "dv": 6.9},
  {"name": "Ft. Hspr. - Front Pike", "entry": "FHS w/ Saltos", "usag": "2.304", "dv": 5.7},
  {"name": "FHS onto board - Ft. Hspr. - Front Pike", "entry": "FHS w/ Saltos", "usag": "2.311", "dv": 5.7},
  {"name": "Ft. Hspr. - Front Pike 1/2", "entry": "FHS w/ Saltos", "usag": "2.404", "dv": 6.0},
  {"name": "FHS onto board - Ft. Hspr. - Front Pike 1/2", "entry": "FHS w/ Saltos", "usag": "2.411", "dv": 6.0},
  {"name": "Ft. Hspr. - 1/2 to Back Pike", "entry": "FHS w/ Saltos", "usag": "2.405", "dv": 6.0},
  {"name": "Ft. Hspr. - Front Pike 1/1", "entry": "FHS w/ Saltos", "usag": "2.408", "dv": 6.6},
  {"name": "Ft. Hspr. - Front Layout", "entry": "FHS w/ Saltos", "usag": "2.406", "dv": 6.6},
  {"name": "Ft. Hspr. - Front Layout 1/2", "entry": "FHS w/ Saltos", "usag": "2.407", "dv": 6.9},
  {"name": "Ft. Hspr. - 1/2 to Back Layout", "entry": "FHS w/ Saltos", "usag": "2.407", "dv": 6.9},
  {"name": "Ft. Hspr. - Front Layout 1/1", "entry": "FHS w/ Saltos", "usag": "2.507", "dv": 7.5},
  {"name": "Ft. Hspr. - Front Layout 3/2", "entry": "FHS w/ Saltos", "usag": "2.508", "dv": 8.1},
  {"name": "Ft. Hspr. - Front Layout 2/1", "entry": "FHS w/ Saltos", "usag": "2.607", "dv": 8.7},
  {"name": "FHS - Double Front Tuck", "entry": "FHS w/ Saltos", "usag": "2.501", "dv": 9.0},
  {"name": "FHS 1/1 On - Front Tuck", "entry": "FHS w/ Saltos", "usag": "2.409", "dv": 7.2},
  {"name": "Ft. Hspr. 1/1 - Front Pike", "entry": "FHS w/ Saltos", "usag": "2.509", "dv": 7.8},
  {"name": "Ft. Hspr. 1/1 - Front Layout", "entry": "FHS w/ Saltos", "usag": "2.609", "dv": 8.4},
  {"name": "Tsuk Tuck", "entry": "Tsukaharas", "usag": "3.201", "dv": 4.8},
  {"name": "Tsuk Tuck 1/2", "entry": "Tsukaharas", "usag": "3.306", "dv": 5.1},
  {"name": "Tsuk Tuck 1/1", "entry": "Tsukaharas", "usag": "3.302", "dv": 5.7},
  {"name": "Ft. Hspr. - 1/2 On to Back Tuck 1/1", "entry": "Tsukaharas", "usag": "3.405", "dv": 5.7},
  {"name": "1/2 On - 1/2 off Front Tuck 1/2", "entry": "Tsukaharas", "usag": "3.308", "dv": 5.7},
  {"name": "Tsuk Tuck 3/2", "entry": "Tsukaharas", "usag": "3.402", "dv": 6.3},
  {"name": "1/2 On - 1/2 off Front Tuck 1/1", "entry": "Tsukaharas", "usag": "3.509", "dv": 6.3},
  {"name": "1/4 On - 1/4 off Front Tuck 3/2", "entry": "Tsukaharas", "usag": "3.508", "dv": 6.9},
  {"name": "Tsuk Pike", "entry": "Tsukaharas", "usag": "3.303", "dv": 5.1},
  {"name": "FHS onto board - 1/2 On - Back Pike", "entry": "Tsukaharas", "usag": "3.305", "dv": 4.8},
  {"name": "Tsuk Pike 1/2", "entry": "Tsukaharas", "usag": "3.307", "dv": 5.4},
  {"name": "Tsuk Pike 1/1", "entry": "Tsukaharas", "usag": "3.403", "dv": 5.4},
  {"name": "Tsuk Layout", "entry": "Tsukaharas", "usag": "3.304", "dv": 5.7},
  {"name": "Tsuk Layout 1/2", "entry": "Tsukaharas", "usag": "3.407", "dv": 6.0},
  {"name": "Tsuk Layout 1/1", "entry": "Tsukaharas", "usag": "3.404", "dv": 6.6},
  {"name": "1/2 On - 1/2 off Front Layout 1/2", "entry": "Tsukaharas", "usag": "3.507", "dv": 6.6},
  {"name": "Tsuk Layout 3/2", "entry": "Tsukaharas", "usag": "3.504", "dv": 7.2},
  {"name": "Tsuk Layout 2/1", "entry": "Tsukaharas", "usag": "3.505", "dv": 7.8},
  {"name": "Tsuk Layout 5/2", "entry": "Tsukaharas", "usag": "3.605", "dv": 8.4},
  {"name": "RO-FF Back Tuck (Yurchenko Tuck)", "entry": "Roundoff Entry w/ Salto", "usag": "4.203", "dv": 4.5},
  {"name": "RO-FF; Back Tuck 1/2", "entry": "Roundoff Entry w/ Salto", "usag": "4.307", "dv": 4.8},
  {"name": "RO-FF - 1/2 Off Front Tuck", "entry": "Roundoff Entry w/ Salto", "usag": "4.307", "dv": 4.8},
  {"name": "RO-FF; Tuck 1/1", "entry": "Roundoff Entry w/ Salto", "usag": "4.303", "dv": 5.4},
  {"name": "RO-FF - 1/2 Off Front Tuck 1/2", "entry": "Roundoff Entry w/ Salto", "usag": "4.407", "dv": 5.4},
  {"name": "RO-FF; Tuck 3/2", "entry": "Roundoff Entry w/ Salto", "usag": "4.403", "dv": 6.0},
  {"name": "RO-FF; Tuck 2/1", "entry": "Roundoff Entry w/ Salto", "usag": "4.503", "dv": 6.6},
  {"name": "RO-FF Back Pike (Yurchenko Pike)", "entry": "Roundoff Entry w/ Salto", "usag": "4.304", "dv": 4.8},
  {"name": "RO-FF; Pike 1/2", "entry": "Roundoff Entry w/ Salto", "usag": "4.308", "dv": 5.1},
  {"name": "RO-FF - 1/2 Off Front Pike", "entry": "Roundoff Entry w/ Salto", "usag": "4.308", "dv": 5.1},
  {"name": "RO-FF - 1/2 Off Front Pike 1/2", "entry": "Roundoff Entry w/ Salto", "usag": "4.508", "dv": 5.7},
  {"name": "RO-FF Back Layout (Yurchenko Layout)", "entry": "Roundoff Entry w/ Salto", "usag": "4.305", "dv": 5.4},
  {"name": "RO-FF; Layout 1/2", "entry": "Roundoff Entry w/ Salto", "usag": "4.309", "dv": 5.7},
  {"name": "RO-FF - 1/2 Off Front Layout", "entry": "Roundoff Entry w/ Salto", "usag": "4.309", "dv": 5.7},
  {"name": "RO-FF; Layout 1/1", "entry": "Roundoff Entry w/ Salto", "usag": "4.306", "dv": 6.3},
  {"name": "RO-FF; Layout 3/2", "entry": "Roundoff Entry w/ Salto", "usag": "4.406", "dv": 6.9},
  {"name": "RO-FF; Layout 2/1", "entry": "Roundoff Entry w/ Salto", "usag": "4.506", "dv": 7.5},
  {"name": "RO-FF; Layout 5/2", "entry": "Roundoff Entry w/ Salto", "usag": "4.606", "dv": 8.1},
  {"name": "RO-FF 1/2 On - Front Tuck", "entry": "Roundoff 1/2 On entry w/ Salto", "usag": "5.301", "dv": 5.7},
  {"name": "RO-FF 1/2 On - Front Tuck 1/2", "entry": "Roundoff 1/2 On entry w/ Salto", "usag": "5.401", "dv": 6.0},
  {"name": "RO-FF 1/2 On - 1/2 off Back Tuck", "entry": "Roundoff 1/2 On entry w/ Salto", "usag": "5.402", "dv": 6.0},
  {"name": "RO-FF 1/2 On - Front Tuck 3/2", "entry": "Roundoff 1/2 On entry w/ Salto", "usag": "5.501", "dv": 7.2},
  {"name": "RO-FF 1/2 On - Front Pike", "entry": "Roundoff 1/2 On entry w/ Salto", "usag": "5.403", "dv": 6.0},
  {"name": "RO-FF 1/2 On - Front Pike 1/2", "entry": "Roundoff 1/2 On entry w/ Salto", "usag": "5.404", "dv": 6.3},
  {"name": "RO-FF 1/2 On - 1/2 off Back Pike", "entry": "Roundoff 1/2 On entry w/ Salto", "usag": "5.405", "dv": 6.3},
  {"name": "RO-FF 1/2 On - Front Layout", "entry": "Roundoff 1/2 On entry w/ Salto", "usag": "5.406", "dv": 6.9},
  {"name": "RO-FF 1/2 On - 1/2 off Back Layout", "entry": "Roundoff 1/2 On entry w/ Salto", "usag": "5.505", "dv": 7.2},
  {"name": "RO-FF 1/2 On - Front Layout 1/2", "entry": "Roundoff 1/2 On entry w/ Salto", "usag": "5.505", "dv": 7.2},
  {"name": "RO-FF 1/1 On - Back Tuck", "entry": "Roundoff 1/1 On entry w/ Salto", "usag": "5.408", "dv": 6.0},
  {"name": "RO-FF 1/1 On - 1/2 off Front Tuck", "entry": "Roundoff 1/1 On entry w/ Salto", "usag": "5.410", "dv": 6.3},
  {"name": "RO-FF 1/1 On - Back Tuck 1/1", "entry": "Roundoff 1/1 On entry w/ Salto", "usag": "5.510", "dv": 6.9},
  {"name": "RO-FF 1/1 On - Back Pike", "entry": "Roundoff 1/1 On entry w/ Salto", "usag": "5.409", "dv": 6.3},
  {"name": "RO-FF 1/1 On - Back Layout", "entry": "Roundoff 1/1 On entry w/ Salto", "usag": "5.509", "dv": 7.2},
  {"name": "RO-FF 1/1 On - Back Layout 1/1", "entry": "Roundoff 1/1 On entry w/ Salto", "usag": "5.511", "dv": 8.1},
];
